inherit_from:
  - ~/.rubocop.yml

AllCops:
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Lint/AssignmentInCondition:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false
