# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2dc6e5b9ffe5c5ff8a24441020b3c5256fb830501c9a9781e3af784c64a1bf1f68f725d7950090bfc31f18a092b640976d7daac69c2b68cc68943e7220ef60c

test:
  secret_key_base: 5e80d0bd643a68b173e523feac04ac63875eb81c15e5c3b35a5a98d4b09850ca8e80dc4756d933e3a6f600ba25f9f2bdcbf4b9d8252d28c8566db2e6a635e585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
